name: law-n-notebooks
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - jupyterlab
  - pandas
  - numpy
  - matplotlib
  - plotly
  - sqlalchemy
  - pip
  - pip:
      - psycopg2-binary
